### ISSUE TITLE
Using `reusableWorkflow.yml@v2` doesn't use latest release

### ISSUE THREAD

**Issue by finestructure** [MarcoEidinger/gha-swift-package-update#10]
I'm not sure if I'm configuring this wrong but I just noticed that [we're pulling in 2.1.3](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3172042531/jobs/5166091062) when 2.1.4 is the latest:

<img width="445" alt="CleanShot 2022-10-03 at 11 43 06@2x" src="https://user-images.githubusercontent.com/65520/193547642-684060af-5d3e-44f4-a8db-397330ad0b6e.png">

Here's [our config](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/package-update/.github/workflows/package-update.yml#L24):

```
    uses: MarcoEidinger/swift-package-dependencies-check/.github/workflows/reusableWorkflow.yml@v2
```

I've picked this config up from the last snippet in the README.

Is our config wrong or is there perhaps an update missing in `reusableWorkflow.yml`?

**Comment by MarcoEidinger** [comment]
Fixed by moving `v2` tag

Now it takes the latest (which is 2.1.4), see https://github.com/MarcoEidinger/swift-package-dependencies-check/blob/v2/.github/workflows/reusableWorkflow.yml
