### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by finestructure** [MarcoEidinger/gha-swift-package-update#14]
I'm seeing a number of warnings [in our logs](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3459029811):

<img width="880" alt="CleanShot 2022-11-14 at 09 22 02@2x" src="https://user-images.githubusercontent.com/65520/201598915-32f286c0-f313-4cda-bcbb-d31130f27e1a.png">

I suspect it's an upstream dependency but I don't know GH actions well enough to spot the issue straight away and didn't dig deeper.

You probably know how to address it immediately, otherwise I'll poke around a bit when I have a minute :)

**Comment by finestructure** [comment]
NB: I don't think it's _our_ action still using checkout@v2, I updated that recently.

**Comment by MarcoEidinger** [comment]
`reusableWorkflow.yml` is using peter-evans/create-pull-request@v3 and using v4 will [get rid of node depreciation warning](https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md#whats-new).

PR will follow to uptake new dependency version

**Comment by MarcoEidinger** [comment]
Also the use of `set-output` in entrypoint.sh needs to be replaced as [those statements are deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

Will follow up on this as well

**Comment by finestructure** [comment]
> `reusableWorkflow.yml` is using peter-evans/create-pull-request@v3 and using v4 will [get rid of node depreciation warning](https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md#whats-new).

Ah great, thanks for the quick reply and for taking a look!

**Comment by MarcoEidinger** [comment]
@finestructure can you test against the main branch that there are no unexpected errors? Once confirmed then I will apply the changes to V2

**Comment by finestructure** [comment]
I'm not sure if I'm doing this the right way or if there's an issue. I've created a [branch `test-pkg-dep`](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/tree/test-pkg-dep) and changed `reusableWorkflow.yml@v2` to `reusableWorkflow.yml@main`. However, that gives me:

```
Error: Unable to resolve action `MarcoEidinger/swift-package-dependencies-check@eliminateWarnings`, unable to find version `eliminateWarnings`
```

when [running the action](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3469886669/jobs/5797417820).

Is this the correct way to test `main`?

**Comment by finestructure** [comment]
Mmm, looks like that branch `eliminateWarnings` does indeed not exist in the repo. Did you perhaps not push it?

**Comment by MarcoEidinger** [comment]
@finestructure sorry that code change was a leftover from earlier testing. I pushed a fix and using main branch should work now

**Comment by finestructure** [comment]
Great, that's working fine now! Thanks for the quick fix!

**Comment by MarcoEidinger** [comment]
Great, I am out of town and will probably update V2 release on Wednesday or Thursday. If you notice any issues in the meantime then please let me know

**Comment by MarcoEidinger** [comment]
Release 2.3.4 got published by me

**Comment by MarcoEidinger** [comment]
V2 points to the latest (2.3.4) release
