### ISSUE TITLE
tools version 5.8 package fails dependency check

### ISSUE THREAD

**Issue by finestructure** [MarcoEidinger/gha-swift-package-update#16]
Hi Marco,

we've updated our repo to be "tools-version 5.8" and that made our [dependency check task](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/4718409053/jobs/8367978610) fail:

```
Changing current directory...
### Current Package Dependencies (swift package show-dependencies)
error: 'workspace': package 'workspace' is using Swift tools version 5.8.0 but the installed version is 5.7.3
### Check and Update Packages Dependencies if they are outdated (swift package update)
#### run swift-release-notes to get details about changes
error: 'workspace': package 'workspace' is using Swift tools version 5.8.0 but the installed version is 5.7.3
Error: error: unexpected input
 --> input:1:1
1 |
  | ^ expected integer
### Run swift package update
error: 'workspace': package 'workspace' is using Swift tools version 5.8.0 but the installed version is 5.7.3
```

I think it's just a matter of bumping the version in the `Dockerfile`, I'll open up a PR.

However, the task also passed all the steps, which I feel it shouldn't in this case:

<img width="482" alt="CleanShot 2023-04-17 at 09 12 39@2x" src="https://user-images.githubusercontent.com/65520/232411301-4b7ed2ac-4279-45e9-a9df-d5525421ec69.png">

**Comment by MarcoEidinger** [comment]
All fixes were merged. New release 2.4.0 created and tag `v2` points to this latest release
