### ISSUE TITLE
Please add support for .xcodeproj files

### ISSUE THREAD

**Issue by mman** [MarcoEidinger/gha-swift-package-update#4]
This looks like a great thing, but would be even better if it can be configured for a repository which is containing an .xcodeproj and uses swift packages as dependencies. I am not familiar enough to see what is needed, but I assume there will be a requirement that `xcodebuild` should be able to update the dependencies from the command line.

This looks to be not possible at the moment. The only swift package manager related option is:

```
xcodebuild -resolvePackageDependencies [-project <projectname>|-workspace <workspacename>] -clonedSourcePackagesDirPath <path>
```

Any ideas?
Thanks for doing this, Martin

**Comment by MarcoEidinger** [comment]
Hi Martin,

thanks for feedback. Your feature request to have a dependency check for an Xcode project on its used Swift packages makes sense for app developers.

But this cannot easily be covered in this GitHub action as it is intended for Swift package developers to check on package dependencies and it uses `swift package` related tooling. A separate GitHub action would be easier. Having said that I did not look into the feasibility or how much tooling would need to be developed to cover that feature request. 

I am leaving this issue open to see if/how many people are potentially be interested and if there volunteers open for collaboration.

**Comment by MarcoEidinger** [comment]
Hi,

@Sherlouk provided GitHub action [action-xcodeproj-spm-update](https://github.com/getsidetrack/action-xcodeproj-spm-update) to resolve SPM dependencies within a Xcode project. I mentioned this GitHub action in the README in a new section "Similiar Packages".

Cheers,
Marco
