### ISSUE TITLE
Action shall fail if it uses an insufficient swift-tools-version

### ISSUE THREAD

**Issue by finestructure** [MarcoEidinger/gha-swift-package-update#8]
We've bumped our tools-version to Swift 5.6 last week and now the [updater is failing](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3172042531/jobs/5166091062) (silently, btw!):

```
### Current Package Dependencies (swift package show-dependencies)
[9](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3172042531/jobs/5166091062#step:4:10)
/github/workspace: error: package at '/github/workspace' is using Swift tools version 5.6.0 but the installed version is 5.5.3
[10](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/actions/runs/3172042531/jobs/5166091062#step:4:11)
```

It would be great if the Swift version was configurable for users of the action.

Also, I don't think the action should pass when it encounters this error :)

**Comment by MarcoEidinger** [comment]
Not sure how or even if that would be configurable. Thank you for your pull request to use Swift 5.7.

I introduced the following releases.
- 2.2.x using Swift 5.6 and
- 2.3.x using Swift 5.7

v2 points to the latest release (currently 2.3.0) and therefore uses Swift 5.7

main branch is using Swift 5.7 as well but uses main branch of https://github.com/SwiftPackageIndex/ReleaseNotes

**Comment by finestructure** [comment]
Thanks for the quick response, Marco!

I suspect making this configurable would be quite complicated, if it's possible at all. I can just open a PR with a version bump in the future, now that I know that's all it'd take.

But it'd be great to have the action fail if this version error occurs. I only happened to see it by chance because I couldn't believe we didn't have any package changes this week (we always do 😅).

Should I open a separate issue for that or do you want to just keep this one open for that?

**Comment by MarcoEidinger** [comment]
> But it'd be great to have the action fail if this version error occurs. I only happened to see it by chance because I couldn't believe we didn't have any package changes this week (we always do 😅).

> Should I open a separate issue for that or do you want to just keep this one open for that?

Let's keep this open and I will have a look at that during the week

**Comment by MarcoEidinger** [comment]
Starting with `2.3.2` (which is also used for `v2`) the action will fail if uses an insufficient swift-tools-version. This will help to notice that a newer GitHub action version needs to be used (or created by myself)
